//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment11st
    {
        public int ID { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string 주문번호 { get; set; }
        public Nullable<int> 주문순번 { get; set; }
        public string 배송번호 { get; set; }
        public string 주문상태 { get; set; }
        public string 구매자명 { get; set; }
        public string 구매자ID { get; set; }
        public Nullable<System.DateTime> 결제완료일 { get; set; }
        public Nullable<System.DateTime> 발송처리일 { get; set; }
        public Nullable<System.DateTime> 배송완료일 { get; set; }
        public Nullable<System.DateTime> 수취확인일 { get; set; }
        public Nullable<System.DateTime> 송금완료일 { get; set; }
        public string 상품번호 { get; set; }
        public string 상품명 { get; set; }
        public string 옵션명 { get; set; }
        public Nullable<int> 수량 { get; set; }
        public Nullable<int> 정산금액 { get; set; }
        public Nullable<int> 판매금액합계 { get; set; }
        public Nullable<int> 추가정산금액합계 { get; set; }
        public Nullable<int> 공제금액합계 { get; set; }
        public Nullable<int> 판매가 { get; set; }
        public Nullable<int> 옵션가 { get; set; }
        public Nullable<int> 선결제배송비 { get; set; }
        public Nullable<int> 도서산간배송비 { get; set; }
        public Nullable<int> 구매자부담_반품_교환배송비 { get; set; }
        public Nullable<int> 반품_교환추가금 { get; set; }
        public Nullable<int> 반품선결제배송비 { get; set; }
        public Nullable<int> 반품도서산간배송비 { get; set; }
        public Nullable<int> 해외취소배송비 { get; set; }
        public Nullable<int> 티켓예매수수료 { get; set; }
        public Nullable<int> 티켓취소예매수수료 { get; set; }
        public Nullable<int> 티켓취소위약금 { get; set; }
        public Nullable<int> 여행취소위약금 { get; set; }
        public string 송장번호 { get; set; }
        public string 서비스이용료정책 { get; set; }
        public string 기본서비스이용율 { get; set; }
        public Nullable<int> 서비스이용료 { get; set; }
        public Nullable<int> 할인쿠폰이용료 { get; set; }
        public Nullable<int> 판매자기본할인 { get; set; }
        public Nullable<int> 판매자추가할인 { get; set; }
        public Nullable<int> C11번가할인 { get; set; }
        public Nullable<int> 복수구매할인비용 { get; set; }
        public Nullable<int> 포인트이용료 { get; set; }
        public Nullable<int> 칩이용료 { get; set; }
        public Nullable<int> 무이자할부이용료 { get; set; }
        public Nullable<int> 후불광고비 { get; set; }
        public Nullable<int> OK캐쉬백_적립부담액 { get; set; }
        public Nullable<int> 지정택배이용료 { get; set; }
        public Nullable<int> 전세계배송_판매자책임반품 { get; set; }
        public Nullable<int> 수출대행수수료 { get; set; }
        public Nullable<int> 물류이용수수료 { get; set; }
    }
}
