//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentAuctionGmarket
    {
        public int ID { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string 아이디 { get; set; }
        public Nullable<System.DateTime> 구매결정일자 { get; set; }
        public string 주문번호 { get; set; }
        public string 상품번호 { get; set; }
        public string 정산상태 { get; set; }
        public Nullable<int> 판매금액 { get; set; }
        public Nullable<int> 판매단가 { get; set; }
        public string 구매자명 { get; set; }
        public string 구매자ID { get; set; }
        public string 상품명 { get; set; }
        public Nullable<int> 수량 { get; set; }
        public string 주문옵션 { get; set; }
        public string 추가구성 { get; set; }
        public string 사은품 { get; set; }
        public string 수령인명 { get; set; }
        public string 수령인_휴대폰 { get; set; }
        public string 수령인_전화번호 { get; set; }
        public string 배송번호 { get; set; }
        public Nullable<int> 배송비_금액 { get; set; }
        public Nullable<System.DateTime> 발송일자 { get; set; }
        public Nullable<System.DateTime> 배송완료일자 { get; set; }
        public string 택배사명_발송방법_ { get; set; }
        public string 송장번호 { get; set; }
        public string 구매자_휴대폰 { get; set; }
        public string 구매자_전화번호 { get; set; }
        public string 장바구니번호_결제번호_ { get; set; }
        public Nullable<System.DateTime> 주문일자_결제확인전_ { get; set; }
        public string 판매자_관리코드 { get; set; }
        public string 판매자_상세관리코드 { get; set; }
        public Nullable<int> 서비스이용료 { get; set; }
        public Nullable<int> 정산예정금액 { get; set; }
        public Nullable<System.DateTime> 주문확인일자 { get; set; }
        public Nullable<int> 판매자쿠폰할인 { get; set; }
        public string 스마일포인트적립 { get; set; }
        public string 일시불할인 { get; set; }
        public string C_옥션_복수구매할인 { get; set; }
        public string C_옥션_우수회원할인 { get; set; }
        public Nullable<System.DateTime> 결제완료일 { get; set; }
        public Nullable<System.DateTime> 정산완료일 { get; set; }
        public string 배송구분 { get; set; }
        public string 주문종류 { get; set; }
        public string SKU번호_및_수량 { get; set; }
        public string 글로벌샵구분 { get; set; }
        public string 해외배송여부 { get; set; }
        public string 제휴사명 { get; set; }
    }
}
