//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesMarket
    {
        public int ID { get; set; }
        public string Market { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<System.DateTime> 일자 { get; set; }
        public string 송장번호 { get; set; }
        public string 수취인명 { get; set; }
        public string 제품명 { get; set; }
        public Nullable<int> 수량 { get; set; }
        public Nullable<int> 공급가 { get; set; }
        public Nullable<int> 택배비 { get; set; }
        public string 주문구분 { get; set; }
        public string 주문번호 { get; set; }
        public string 상품코드 { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    }
}
